"""time task

Revision ID: 06ca6dab7886
Revises: b279d2a7fd19
Create Date: 2020-06-08 17:20:34.993407

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06ca6dab7886'
down_revision = 'b279d2a7fd19'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('task', sa.Column('finish_time', sa.DateTime(), nullable=True))
    op.add_column('task', sa.Column('start_time', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task', 'start_time')
    op.drop_column('task', 'finish_time')
    # ### end Alembic commands ###
