"""new task3

Revision ID: b279d2a7fd19
Revises: 4e030963c351
Create Date: 2020-06-05 17:29:33.352183

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b279d2a7fd19'
down_revision = '4e030963c351'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('table_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'table_id')
    # ### end Alembic commands ###
