"""fix item table

Revision ID: c60ab5cf4145
Revises: 06ca6dab7886
Create Date: 2020-06-11 12:49:30.770394

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c60ab5cf4145'
down_revision = '06ca6dab7886'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item_table', sa.Column('index', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('item_table', 'index')
    # ### end Alembic commands ###
